# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/paper',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/paper',
                'lib_path': 'paper'},
  'syms': {'paper.core': {'paper.core.foo': ('core.html#foo', 'paper/core.py')}}}
